# Generated by Django 5.0.6 on 2024-06-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pages_recipee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255)),
                ('ingredients', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=255)),
                ('quantity', models.TextField(max_length=255)),
                ('course', models.CharField(choices=[('appetizers', 'Appetizers'), ('main_course', 'Main Course'), ('dessert', 'Dessert')], max_length=50)),
            ],
        ),
    ]
